### ISSUE TITLE
Coverage calculated against test project rather than main project

### ISSUE THREAD

**Issue by 8bitorbust** [Rogeriohsjr/CoverageConverter#10]
I've implemented this in my devops pipeline against a solution which has a new test project with a single test. When using visual studio I get back a coverage of 0.98%. In devops this is reporting 100%. I look at the details and it seems its calculating the coverage against the tests project rather than the main project in the solution. The report only shows the dll for test project.

**Comment by Rogeriohsjr** [comment]
Hey @8bitorbust , could you share how you setup the code coverage?
I would recommend you to change the Test Files from **\bin\**\*.Tests*.dll to be more specific about your Project Name. That might help.
