### ISSUE TITLE
How to remove warning

### ISSUE THREAD

**Issue by inganibalguerra** [Rogeriohsjr/CoverageConverter#7]
2020-09-04T02:20:08: Report generation took 7.7 seconds
Generated code coverage html report: D:\a\_temp\cchtml
##[warning]Ignoring coverage report directory with Html content as we are auto-generating Html content
Reading code coverage summary from 'D:\a\1\s\TestResults\Coverage\Reports\Cobertura.xml'

**Comment by Rogeriohsjr** [comment]
Hey @inganibalguerra , I don't have any idea, the task that shows this message is "Publish Coverage Report" which is from Microsoft, I would suggest you to contact them.
I also get this message, but that doesn't impact on anything in my side, I can still see the Report in Code Coverage Tab.

"2020-06-04T21:28:56: Report generation took 0.3 seconds
Generated code coverage html report: D:\a\_temp\cchtml
##[warning]Ignoring coverage report directory with Html content as we are auto-generating Html content
Reading code coverage summary from 'D:\a\1\s\TestResults\Coverage\Reports\Cobertura.xml'
Async Command Start: Publish code coverage
Publishing coverage summary data to TFS server.
 Lines- 43 of 99 covered.
 Branches- 0 of 0 covered.
Modifying Cobertura Index file
Publishing code coverage files to TFS server.
Uploading 15 files
File upload succeed.
Published 'D:\a\_temp\cchtml' as artifact 'Code Coverage Report_47'
Async Command End: Publish code coverage
Finishing: Publish Coverage Report
"

**Comment by inganibalguerra** [comment]
Thank you very much friend, forgive my English :)
I am new to code coverage, I have always developed with the community version of visual studio and had not had the opportunity to verify coverage and less in a pipeline. I appreciate your great contribution, however I would like to know how to avoid or ignore the coverage for some dll like these:
nunit.framework.dll
nunit3.testadapter.dll

Any help would be very important to me :)

And about the warning, I agree it has no negative impact.
