### ISSUE TITLE
Coverage Converter Extension is failing to generate coverage file

### ISSUE THREAD

**Issue by SRP07** [Rogeriohsjr/CoverageConverter#9]
Hi,

I am using the Coverage Converter Extension in my Azure DevOps pipeline after the VS Test task and the Coverage converter extension is failing with the below error.

I want to display the code coverage on the build summary. Could anyone please let me know why is it failing? 
Have attached the log of Coverage Convertor and VS test task as well. 

**Generating coverage for file [e:\cache\Agent03\18\s\packages\MSTest.TestAdapter.1.2.1\build\_common\ko\Microsoft.VisualStudio.TestPlatform.TestFramework.resources.dll]
Generating coverage for file [e:\cache\Agent03\18\s\packages\MSTest.TestAdapter.1.2.1\build\_common\pl\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.resources.dll]
[run] Error unexpected! Error[spawnSync C:\Windows\system32\cmd.exe ENAMETOOLONG] { Error: spawnSync C:\Windows\system32\cmd.exe ENAMETOOLONG
    at Object.spawnSync (internal/child_process.js:1002:20)
    at spawnSync (child_process.js:614:24)
    at Object.execSync (child_process.js:661:13)
    at executeVsTestCodeCoverage (e:\cache\Agent03\_tasks\CoverageConverter_aec0730c-83af-458f-92b8-37e81a9fed9d\0.1.24\index.js:43:21)
    at e:\cache\Agent03\_tasks\CoverageConverter_aec0730c-83af-458f-92b8-37e81a9fed9d\0.1.24\index.js:20:13
    at Generator.next (<anonymous>)
    at e:\cache\Agent03\_tasks\CoverageConverter_aec0730c-83af-458f-92b8-37e81a9fed9d\0.1.24\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (e:\cache\Agent03\_tasks\CoverageConverter_aec0730c-83af-458f-92b8-37e81a9fed9d\0.1.24\index.js:4:12)
    at run (e:\cache\Agent03\_tasks\CoverageConverter_aec0730c-83af-458f-92b8-37e81a9fed9d\0.1.24\index.js:16:12)
  errno: 'ENAMETOOLONG',
  code: 'ENAMETOOLONG',
  syscall: 'spawnSync C:\\Windows\\system32\\cmd.exe',
  path: 'C:\\Windows\\system32\\cmd.exe',
  spawnargs:
   [ '/d',
     '/s',
     '/c',
     '""C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe" "e:\\cache\\Agent03\\18\\s\\PSP.Common.Implementation.Tests\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Common.Implementation.Tests\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Common.Implementation.Tests\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Common.Implementation.Tests\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.TestFramework.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Common.Implementation.Tests\\bin\\Release\\PSP.Common.Implementation.Tests.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Configuration.Implementation.Tests\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Configuration.Implementation.Tests\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Configuration.Implementation.Tests\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Configuration.Implementation.Tests\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.TestFramework.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Configuration.Implementation.Tests\\bin\\Release\\PSP.Configuration.Implementation.Tests.dll" "e:\\cache\\Agent03\\18\\s\\PSP.Cryptography.Implementation.Test\\bin\\Release\\Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll" "e:\\cache\\Agent03\\18\\s\\packages\\MSTest.TestFramework.1.4.0\\lib\\net45\\Microsoft.VisualStudio.TestPlatform.TestFramework.dll" "e:\\cache\\Agent03\\18\\s\\packages\\MSTest.TestFramework.1.4.0\\lib\\netstandard1.0\\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" "e:\\cache\\Agent03\\18\\s\\packages\\MSTest.TestFramework.1.4.0\\lib\\netstandard1.0\\Microsoft.VisualStudio.TestPlatform.TestFramework.dll" "e:\\cache\\Agent03\\18\\s\\packages\\MSTest.TestFramework.1.4.0\\lib\\uap10.0\\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll" "e:\\cache\\Agent03\\18\\s\\packages\\MSTest.TestFramework.1.4.0\\lib\\uap10.0\\Microsoft.VisualStudio.TestPlatform.TestFramework.dll"  /EnableCodeCoverage"' ],
  error: [Circular],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null }**

[15_VsTest - testAssemblies.txt](https://github.com/Rogeriohsjr/CoverageConverter/files/7265732/15_VsTest.-.testAssemblies.txt)
[Coverage Converter.txt](https://github.com/Rogeriohsjr/CoverageConverter/files/7265735/Coverage.Converter.txt)

**Comment by Rogeriohsjr** [comment]
Hey @SRP07 , 

Thanks for using the app.
I took a look in the error and it seems that you need to be more specific in your criteria to find the tests. It seems that you have a lot of projects and tests to run, so when the tool try to read all the test and execute the convert we are getting error saying the name of the files is too long.

I would recommend you to try to change your filter for the tests.
In Test Files option, try this:
**\bin\**\PSP.*.Tests*.dll

The idea with this filter is to get only tests from your Project, which seems to start with PSP.***

If that still showing the error and we are getting only those files. So try for a specific project like:
In Test Files option, try this:
**\bin\**\PSP.SOIManager.Implementation.Tests*.dll

If you get the error post the log again please. Let me know how it goes.

**Comment by SRP07** [comment]
Hi Rogeriohsjr,

Thanks for your reply, I tried running the tasks with the filter that you had mentioned in your reply but I got the below errors.

Also, which filter pattern is supported for Test Files option in your task is it the same this is supported for VS Test task? Is it the below one supported,
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

Here are the logs for the error, 
1. Echo (Coverage Converter) task failed when used Test file as **\bin\**\*.Tests*.dll
[16_Echo.txt](https://github.com/Rogeriohsjr/CoverageConverter/files/7276586/16_Echo.txt)

2.  Echo task failed when used Test file as **\bin*\PSP..Tests*.dll
[3_Echo.txt](https://github.com/Rogeriohsjr/CoverageConverter/files/7276599/3_Echo.txt)

3. Echo task failed when used Test file as **\bin*\PSP.SOIManager.Implementation.Tests.dll
[4_Echo.txt](https://github.com/Rogeriohsjr/CoverageConverter/files/7276611/4_Echo.txt)


Also attaching the log of successfully executed VS test task for reference, 
[3_VsTest - testAssemblies.txt](https://github.com/Rogeriohsjr/CoverageConverter/files/7276627/3_VsTest.-.testAssemblies.txt)

**Comment by Rogeriohsjr** [comment]
Hey @SRP07 ,

We use findMatch.
https://github.com/Rogeriohsjr/CoverageConverter/blob/a89b3a5f1555a90e57a1dece9525aac1f9a9510b/buildAndReleaseTask/index.ts#L106

1. Your first example has filtered better, that is an advance, but for some reason we still showing an error.

2. My bad, I forgot one *(star) between PSP and Test, but your first example filtered what I wanted before. SO we can ignore this.

3. This one it is missing one *(star), in my example I said: **\bin*\PSP.SOIManager.Implementation.Tests.dll in your example you said: *\bin\PSP.SOIManager.Implementation.Tests.dll, this one should filter one project to see if it works.

Another test I would say, try one project, like the third example and see if it pass. I think you solved the first issue of the name too long, now we have another issue happening, which is in the log from the first example.

Let me know how it goes.
